# schedule
day1: Tuesdays
time1: 11 AM - 1 PM
loc1: <strong>SF-1101</strong> - <em>Sandford Fleming Building</em>

day2: Fridays
time2: 11 AM - 1 PM
loc2: <strong>MP-103</strong> - <em>McLennan Physical Laboratories</em>

dayTut: TBA
timeTut: TBA
locTut: <strong>TBA</strong> - <em>TBA</em>

start_date: September 2, 2025
start_description: Please note that the lecture halls are different in Tuesdays and Fridays.

start_dateTut: TBA

dayOffice: TBA 
timeOffice: TBA

# Site settings
course_name: Applied Deep Learning
course_description: "The key goal of this course is to provide a fundamental understanding on Computational Learning, its functionality, and its deployment towards building information processing units. These concepts are keys to Deep Learning and its Applications. The course is designed to give a good mixture of fundamental notions and hands-on skills by teaching both theory of deep learning and recent advances in this area."
course_semester: "Fall 2025"


assgn_mark: 45%
assgn_desc: "4 assignment sets"
assgn_txt: "No need to say that this is the most important part! We are learning Deep Learning. This means that we should get our hands dirty and implement whatever we learn. There will be four set of assignments. Roughly speaking, the first one goes through basics and make you get into the mood of the course. The next three go through MLPs, CNNs and Sequence Models. There will be also some optional items for self-practice. The assignments will count roughly for 45% of your final mark."

exam_mark: 25%
exam_desc: "midterm exam"
exam_txt: "Let us call it midterm, but to be fair it would be a theory-side-of-the-course exam! When we are over with the fundamental topics, somewhere halfway through Step 2 in Week 8, there will be an exam. The exam will ask questions on theory. There will be of course no programming questions in the exam! The exam will only evaluate the understanding of fundamental concepts through questions that can be either explained in words or solved simply by hand. This exam will comprise 25% of the total mark."

project_mark: 30%
project_desc: "open-ended"
project_txt: "Last but not the least, there will be a final project. This is the exciting part of the course, where we could challenge ourselves and test the development of our skills! Each group suggests its own problem that is to be solved by Deep Learning. Each group will then work on the project through the semester and present its final result at the end in a report and a short presentation. Doing this project, we will build self-confidence that we are now experts in Deep Learning. This part will be 30% of the total mark. Note that the final projects plays the role of final evaluation for this course."


baseurl: "/dl-utoronto" # the subpath of your site, e.g. /blog/
url: "https://bereyhi-courses.github.io/" # the base hostname & protocol for your site

schoolname: "University of Toronto"
schoolurl: "https://www.ece.utoronto.ca"
personal_page: "bereyhi.com"

address: |
    The Edward S. Rogers Sr. Department of Electrical and Computer Engineering
    University of Toronto

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

minima:
  include_css:
    - /assets/css/custom.css

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include:
  - assets
  - _images
  - _css

exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
